#!/bin/zsh

set -v

# Generate static documentation files into the `docs` folder.

# Uses --experimental-skip-synthesized-symbols as a workaround to the documentation of standard
# library protocols changing randomly on every rebuild.
# See https://github.com/lopsae/docc-extensions-issue

swift package --allow-writing-to-directory ./docs \
    generate-documentation --target "PreviewUtilities" \
    --disable-indexing \
    --experimental-skip-synthesized-symbols \
    --transform-for-static-hosting \
    --hosting-base-path "/preview-utilities" \
    --output-path ./docs


# Prettify jsons, to minimize changes upon rebuild.
find ./docs -name "*.json" -print0 | \
    xargs --null --max-args=1 --max-procs="$(sysctl -n hw.ncpu)" \
    sh -c 'jq --monochrome-output --indent 2 --sort-keys . "$1" > "$1.tmp" && mv "$1.tmp" "$1"' _

