name: Deploy to GitHub Pages

on:
  push:
    branches: ["documentation/main", "documentation/develop"]
  workflow_dispatch:

jobs:
  branch-guard:
    runs-on: ubuntu-latest
    steps:
      - name: Fail on package branches
        uses: actions/github-script@v9
        with:
          script: |
            core.setFailed("This workflow should only run in `documentation` branches.")
